name: Deploy HTML/CSS to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # This points to your root directory if your HTML/CSS files are there
          publish_branch: gh-pages  # Deploy to the 'gh-pages' branch
